/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "debugbar.openhandler": [],
    "debugbar.clockwork": [
        {
            "name": "id"
        }
    ],
    "debugbar.assets.css": [],
    "debugbar.assets.js": [],
    "debugbar.cache.delete": [
        {
            "name": "key"
        },
        {
            "name": "tags"
        }
    ],
    "api.token-get": [],
    "api.token-renew": [],
    "apdoc.api-documentation": [],
    "apdoc.json": [],
    "welcome": [],
    "utils.subscription": [
        {
            "name": "type"
        }
    ],
    "guide.login": [],
    "guide.login.store": [],
    "guide.register": [],
    "guide.register.store": [],
    "guide.home": [],
    "guide.home.search": [
        {
            "name": "search"
        }
    ],
    "guide.logout": [],
    "guide.home.merchant-categories": [
        {
            "name": "category"
        }
    ],
    "guide.order.guide": [],
    "guide.merchants.index": [],
    "guide.merchants.index-data": [],
    "guide.merchants.detail": [
        {
            "name": "id"
        }
    ],
    "guide.merchants.booking": [
        {
            "name": "id"
        }
    ],
    "guide.merchants.category": [
        {
            "name": "category"
        }
    ],
    "guide.merchants.featured": [
        {
            "name": "featured"
        }
    ],
    "guide.merchants.category-data": [
        {
            "name": "type"
        },
        {
            "name": "category"
        }
    ],
    "guide.products.category": [
        {
            "name": "category"
        }
    ],
    "guide.products.category-data": [
        {
            "name": "category"
        }
    ],
    "guide.qrcode.index": [],
    "guide.qrcode.histories.scan": [],
    "guide.qrcode.histories.scan-data": [],
    "guide.qrcode.histories.booking": [],
    "guide.qrcode.histories.booking-data": [],
    "guide.inbox.merchant": [],
    "guide.inbox.admin": [],
    "guide.inbox.merchant-data": [],
    "guide.inbox.admin-data": [],
    "guide.profile.index": [],
    "guide.profile.detail": [],
    "guide.profile.edit": [],
    "guide.profile.change-password": [],
    "guide.feedback.complaint": [],
    "merchant.login": [],
    "merchant.login.store": [],
    "merchant.register": [],
    "merchant.register.store": [],
    "merchant.home": [],
    "merchant.home.edit": [],
    "merchant.home.edit.store": [],
    "merchant.inbox.index": [],
    "merchant.inbox.index-data": [],
    "merchant.member.index": [],
    "merchant.member.index-data": [],
    "merchant.logout": [],
    "merchant.products.add": [],
    "merchant.products.store": [],
    "merchant.products.detail": [
        {
            "name": "id"
        }
    ],
    "merchant.products.edit": [
        {
            "name": "id"
        }
    ],
    "merchant.products.edit.update": [
        {
            "name": "id"
        }
    ],
    "merchant.order.merchant": [],
    "merchant.order.product": [
        {
            "name": "id"
        }
    ],
    "merchant.order.merchant.histories": [],
    "merchant.order.merchant.histories-data": [],
    "merchant.profile.index": [],
    "merchant.profile.change-password": [],
    "merchant.qrcode.index": [],
    "merchant.qrcode.histories": [],
    "merchant.qrcode.histories-data": [],
    "merchant.qrcode.check-qr": [
        {
            "name": "token"
        }
    ],
    "merchant.qrcode.reservation": [
        {
            "name": "id"
        }
    ],
    "merchant.feedback.complaint": []
}
}
export {};
